### ISSUE TITLE
[Request] Enable Ctrl+/ to to create/remove blocks of comments.

### ISSUE THREAD

**Issue by jbblanchet** [teroparvinen/foundry-improved-macro-editor#2]
First of, thank you for this. Was trying to edit my first macro yesterday and I was pulling my hair out.

I'll submit a couple of ideas for improvement as issues. I'm unclear on the work required whether they're realistic or not. If you do not plan on implementing them, feel free to close them up, no hard feeling. Appreciate the features already in place. Thanks. 

----------------------

Action: I select a few lines of code and press Ctrl+/ (or equivalent on Mac)

Expected result: Lines are commented out if they weren't already, or uncommented if they all were.

Current result: All lines in the window become selected

**Comment by teroparvinen** [comment]
Did you set the keybinding for the block comment command? If you did, can you try another binding just to test?

Unfortunately, I don't have a windows machine or an actual US keyboard at hand to test. I did switch my keyboard layout to US and tried Cmd+/ (Foundry wouldn't let me put it on Ctrl) and it works ok.

These can be tricky on a browser (which Foundry is), so any clues at all as to what might be causing the trouble would be appreciated.

**Comment by jbblanchet** [comment]
Ah! Just found the setting in configure controls. Didn't think of looking there. Sorry about that.
