### ISSUE TITLE
v11 update?

### ISSUE THREAD

**Issue by CapivaraTupiniquim** [teroparvinen/foundry-improved-macro-editor#9]
I like this module and would like to know if it will be updated to v11. First of all, thank you!

**Comment by teroparvinen** [comment]
Yes it will, but I am not aware of any issues other than not having the V11 verified status in the module list. Are you seeing errors or similar?

**Comment by CapivaraTupiniquim** [comment]
No apparent errors. I just missed compatibility with the Template Macros module, but there is already an open issue for that.
